const GalleryActionTypes = {
    FETCH_GALLERY: 'FETCH_GALLERY',
    SET_GALLERY :  'SET_GALLERY',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_CURRENT_CATEGORY:'SET_CURRENT_CATEGORY',
    FETCH_GALLERY_REQUEST:'FETCH_GALLERY_REQUEST',
    FETCH_GALLERY_FAILURE:'FETCH_GALLERY_FAILURE'
}

export default GalleryActionTypes