const GalleryActionTypes = {
        FETCH_GALLERY_REQUEST:'FETCH_GALLERY_REQUEST',
        FETCH_GALLERY_SUCCESS:'FETCH_GALLERY_SUCCESS',  
        FETCH_GALLERY_FAILURE:'FETCH_GALLERY_FAILURE',
        SET_CATEGORIES: 'SET_CATEGORIES',
        SET_CURRENT_CATEGORY:'SET_CURRENT_CATEGORY',
        // RESET_STORE: 'RESET_STORE'
    // FETCH_GALLERY: 'FETCH_GALLERY',
    // SET_GALLERY :  'SET_GALLERY',
    // SET_CATEGORIES: 'SET_CATEGORIES',
    // SET_CURRENT_CATEGORY:'SET_CURRENT_CATEGORY',
    // FETCH_GALLERY_REQUEST:'FETCH_GALLERY_REQUEST',
    // FETCH_GALLERY_FAILURE:'FETCH_GALLERY_FAILURE'
}

export default GalleryActionTypes