const GalleryActionTypes = {
  FETCH_GALLERY_REQUEST: "FETCH_GALLERY_REQUEST",
  FETCH_GALLERY_SUCCESS: "FETCH_GALLERY_SUCCESS",
  FETCH_GALLERY_FAILURE: "FETCH_GALLERY_FAILURE",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
  RESET_GALLERY: "RESET_GALLERY",
};

export default GalleryActionTypes;
